import { describe, expect, it } from 'vitest';

import {
  assertIssueNumber,
  assertRunId,
  branchNameForIssue,
  createRunId,
  formatAfkMarker,
  parseAfkMarker,
  workspaceNameForIssue,
} from '../../../.sandcastle/lib/afkIdentity.js';

describe('assertIssueNumber', () => {
  it('returns a valid issue number', () => {
    expect(assertIssueNumber(42)).toBe(42);
  });

  it('rejects zero and negative numbers', () => {
    expect(() => assertIssueNumber(0)).toThrow(/positive integer/u);
    expect(() => assertIssueNumber(-1)).toThrow(/positive integer/u);
  });

  it('rejects fractional and non-finite numbers', () => {
    expect(() => assertIssueNumber(1.5)).toThrow(/positive integer/u);
    expect(() => assertIssueNumber(Number.NaN)).toThrow(/positive integer/u);
    expect(() => assertIssueNumber(Number.POSITIVE_INFINITY)).toThrow(
      /positive integer/u,
    );
  });
});

describe('assertRunId', () => {
  it('accepts a compact UTC run ID', () => {
    expect(assertRunId('20260430T141500Z')).toBe('20260430T141500Z');
  });

  it('rejects extended ISO-8601 run IDs', () => {
    expect(() => assertRunId('2026-04-30T14:15:00Z')).toThrow(/compact UTC/u);
  });

  it('rejects non-string values', () => {
    expect(() => assertRunId(20260430)).toThrow(/compact UTC/u);
  });
});

describe('createRunId', () => {
  it('formats a fixed Date as a compact UTC run ID', () => {
    expect(createRunId(new Date(Date.UTC(2026, 3, 30, 14, 15, 0)))).toBe(
      '20260430T141500Z',
    );
  });

  it('zero-pads single-digit fields', () => {
    expect(createRunId(new Date(Date.UTC(2026, 0, 1, 1, 2, 3)))).toBe(
      '20260101T010203Z',
    );
  });

  it('returned value round-trips through assertRunId', () => {
    const runId = createRunId(new Date(Date.UTC(2026, 11, 31, 23, 59, 59)));
    expect(assertRunId(runId)).toBe(runId);
  });
});

describe('branchNameForIssue', () => {
  it('builds the triage branch name for an issue and run ID', () => {
    expect(branchNameForIssue(123, '20260430T141500Z')).toBe(
      'afk-triage/123-20260430T141500Z',
    );
  });

  it('rejects an invalid run ID', () => {
    expect(() => branchNameForIssue(123, '2026-04-30T14:15:00Z')).toThrow(
      /compact UTC/u,
    );
  });

  it('rejects an invalid issue number', () => {
    expect(() => branchNameForIssue(0, '20260430T141500Z')).toThrow(
      /positive integer/u,
    );
  });
});

describe('workspaceNameForIssue', () => {
  it('builds the Coder workspace name for an issue', () => {
    expect(workspaceNameForIssue(123)).toBe('agent-tty-triage-123');
  });

  it('rejects an invalid issue number', () => {
    expect(() => workspaceNameForIssue(0)).toThrow(/positive integer/u);
  });
});

describe('AFK marker helpers', () => {
  it('formats and parses a valid marker', () => {
    const marker = formatAfkMarker({
      issue: 123,
      outcome: 'ready-for-agent',
      run: '20260430T141500Z',
    });

    expect(marker).toBe(
      '<!-- afk-triage:v1 issue=123 outcome=ready-for-agent run=20260430T141500Z -->',
    );
    expect(parseAfkMarker(marker)).toEqual({
      issue: 123,
      outcome: 'ready-for-agent',
      run: '20260430T141500Z',
    });
  });

  it('parses a marker embedded after the disclaimer text', () => {
    expect(
      parseAfkMarker(`> *This was generated by AI during triage.*
<!-- afk-triage:v1 issue=456 outcome=needs-info run=20260430T141500Z -->

Needs reporter input.`),
    ).toEqual({
      issue: 456,
      outcome: 'needs-info',
      run: '20260430T141500Z',
    });
  });

  it('returns null for an invalid outcome', () => {
    expect(
      parseAfkMarker(
        '<!-- afk-triage:v1 issue=123 outcome=closed run=20260430T141500Z -->',
      ),
    ).toBeNull();
  });

  it('returns null when the issue capture is zero', () => {
    expect(
      parseAfkMarker(
        '<!-- afk-triage:v1 issue=0 outcome=needs-info run=20260430T141500Z -->',
      ),
    ).toBeNull();
  });

  it('returns null when the run ID is not compact UTC format', () => {
    expect(
      parseAfkMarker(
        '<!-- afk-triage:v1 issue=123 outcome=needs-info run=2026-04-30T14:15:00Z -->',
      ),
    ).toBeNull();
  });

  it('rejects an invalid run ID when formatting', () => {
    expect(() =>
      formatAfkMarker({
        issue: 123,
        outcome: 'ready-for-agent',
        run: '2026-04-30T14:15:00Z',
      }),
    ).toThrow(/compact UTC/u);
  });
});
