import { describe, expect, it } from 'vitest';

import {
  formatAfkMarker,
  parseAfkMarker,
} from '../../../.sandcastle/lib/afkMarker.js';

describe('AFK marker helpers', () => {
  it('formats and parses a valid marker', () => {
    const marker = formatAfkMarker({
      issue: 123,
      outcome: 'ready-for-agent',
      run: '20260430T141500Z',
    });

    expect(marker).toBe(
      '<!-- afk-triage:v1 issue=123 outcome=ready-for-agent run=20260430T141500Z -->',
    );
    expect(parseAfkMarker(marker)).toEqual({
      issue: 123,
      outcome: 'ready-for-agent',
      run: '20260430T141500Z',
    });
  });

  it('parses a marker embedded after the disclaimer text', () => {
    expect(
      parseAfkMarker(`> *This was generated by AI during triage.*
<!-- afk-triage:v1 issue=456 outcome=needs-info run=20260430T141500Z -->

Needs reporter input.`),
    ).toEqual({
      issue: 456,
      outcome: 'needs-info',
      run: '20260430T141500Z',
    });
  });

  it('returns null for an invalid outcome', () => {
    expect(
      parseAfkMarker(
        '<!-- afk-triage:v1 issue=123 outcome=closed run=20260430T141500Z -->',
      ),
    ).toBeNull();
  });

  it('rejects an invalid run ID when formatting', () => {
    expect(() =>
      formatAfkMarker({
        issue: 123,
        outcome: 'ready-for-agent',
        run: '2026-04-30T14:15:00Z',
      }),
    ).toThrow(/compact UTC/u);
  });
});
